default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: akita
  password: 123456
  host: localhost

development:
  <<: *default
  database: TOP_Social_development

test:
  <<: *default
  database: TOP_Social_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
